name: school_village
description: School Village

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  firebase_core: ^0.2.5+1
  cloud_firestore: ^0.8.2+3
  firebase_analytics: ^1.0.6
  firebase_auth: ^0.6.5
  firebase_storage: ^1.0.4
  firebase_messaging: ^2.1.0
  shared_preferences: ^0.4.3
  crypto: 2.0.6
  path_provider: ^0.4.1
  url_launcher: ^3.0.3
  location: ^1.4.1
  http: ^0.12.0
  sentry: 2.1.1
  device_info: ^0.3.0
  scoped_model: ^0.3.0
  audioplayers: ^0.7.8
  flutter_html_view: ^0.5.10
  intl: any
  intl_translation: any
  image_picker: ^0.4.10
  photo_view: 0.0.11
  package_info: ^0.3.2
  video_player: 0.7.2


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/pdf/safety.pdf
    - assets/images/logo.png
    - assets/images/alert.png
    - assets/images/alert_armed.png
    - assets/images/alert_fire.png
    - assets/images/alert_intruder.png
    - assets/images/alert_other.png
    - assets/images/alert_medical.png
    - assets/images/alert_fight.png
    - assets/images/splash_text.png
    - assets/images/broadcast_btn.png
    - assets/images/security_btn.png
    - assets/images/alert_hand_icon.png
    - assets/images/hotline_header.png
    - assets/images/hotline_bg.png
    - assets/images/camera.png
    - assets/images/incident_type.png
    - assets/images/incident_details.png
    - assets/audio/alarm.wav
    - assets/audio/message.wav

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies, 
  # see https://flutter.io/custom-fonts/#from-packages
