name: school_village
description: School Village
version: 1.4.1+1

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cloud_firestore: 0.14.0-dev.1
  firebase_analytics: 5.0.14
  firebase_auth: 0.17.0-dev.1
  firebase_storage: 4.0.0
  firebase_messaging: 6.0.16
  shared_preferences: 0.5.7+3
  crypto: 2.1.4
  path_provider: 1.6.9
  url_launcher: 5.4.10
  location: 3.0.2
  http: 0.12.1
  sentry: 3.0.1
  device_info: 0.4.2+4
  scoped_model: 1.0.1
  audioplayers: 0.15.1
  intl: 0.16.1
  intl_translation: 0.17.9
  image_picker: 0.6.7
  photo_view: 0.9.2
  package_info: 0.4.0+18
  awsome_video_player: 1.0.8+1
  modal_progress_hud: 0.1.3
  flutter_ffmpeg: 0.2.10
  progress_hud: 1.1.0
  google_maps_flutter: 0.5.28+1
  rxdart: 0.24.1
  pdftron_flutter:
    git:
      url: git://github.com/PDFTron/pdftron-flutter.git



dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/pdf/safety.pdf
    - assets/images/logo.png
    - assets/images/alert.png
    - assets/images/alert_armed.png
    - assets/images/alert_fire.png
    - assets/images/alert_intruder.png
    - assets/images/alert_other.png
    - assets/images/alert_medical.png
    - assets/images/alert_fight.png
    - assets/images/splash_text.png
    - assets/images/broadcast_btn.png
    - assets/images/security_btn.png
    - assets/images/alert_hand_icon.png
    - assets/images/hotline_header.png
    - assets/images/hotline_bg.png
    - assets/images/camera.png
    - assets/images/incident_type.png
    - assets/images/incident_details.png
    - assets/images/feature_image.png
    - assets/images/incident_management_icon.png
    - assets/images/group_message_btn.png
    - assets/images/sop_btn.png
    - assets/images/stop_sign.png
    - assets/images/warning_sign.png
    - assets/images/anonymous_img.png
    - assets/images/sv_icon_menu.png
    - assets/images/incident_report_log.png
    - assets/images/add_dm_user_btn.png
    - assets/images/school_map_btn.png
    - assets/audio/alarm.wav
    - assets/audio/message.wav

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies, 
  # see https://flutter.io/custom-fonts/#from-packages
