name: school_village
description: School Village

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  firebase_core: ^0.4.0+1
  cloud_firestore: ^0.11.0+2
  firebase_analytics: ^3.0.1
  firebase_auth: ^0.11.1
  firebase_storage: ^3.0.0
  firebase_messaging: ^5.0.1+1
  shared_preferences: ^0.5.2
  crypto: 2.0.6
  path_provider: ^1.1.0
  url_launcher: ^5.0.2
  location: ^2.3.5
  http: ^0.12.0+2
  sentry: 2.2.0
  device_info: ^0.4.0+1
  scoped_model: ^1.0.1
  audioplayers: ^0.12.0
  intl: any
  intl_translation: any
  image_picker: ^0.6.0+3
  photo_view: 0.3.3
  package_info: ^0.4.0+3
  video_player: 0.10.1
  modal_progress_hud: 0.1.3
  flutter_ffmpeg: ^0.2.1
  progress_hud: 1.1.0
  mime: 0.9.6+2



dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/pdf/safety.pdf
    - assets/images/logo.png
    - assets/images/alert.png
    - assets/images/alert_armed.png
    - assets/images/alert_fire.png
    - assets/images/alert_intruder.png
    - assets/images/alert_other.png
    - assets/images/alert_medical.png
    - assets/images/alert_fight.png
    - assets/images/splash_text.png
    - assets/images/broadcast_btn.png
    - assets/images/security_btn.png
    - assets/images/alert_hand_icon.png
    - assets/images/hotline_header.png
    - assets/images/hotline_bg.png
    - assets/images/camera.png
    - assets/images/incident_type.png
    - assets/images/incident_details.png
    - assets/images/feature_image.png
    - assets/audio/alarm.wav
    - assets/audio/message.wav

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies, 
  # see https://flutter.io/custom-fonts/#from-packages
