# iOS CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/ios-migrating-from-1-2/ for more details
#
version: 2
jobs:
  build-ios-beta:
    macos:
      xcode: "9.2.0"

    steps:
      - checkout
      - run: cd ios && pod install
      - run: cd .. && flutter doctor
      - run: flutter build ios --release
      - run: cd ios && fastlane deploy_beta

  build-android-beta:
    docker:
      - image: cirrusci/flutter

    steps:
      - checkout
      - run: flutter doctor
      - run: flutter build apk --release
      - run: cd android && fastlane add_plugin appcenter
      - run: fastlane deploy_beta

workflows:
  version: 2

  beta:
    jobs:
      - build-ios-beta
      - build-android-beta
