version: 2
jobs:

  build-ios-beta:
    macos:
      xcode: "9.2.0"
    steps:
      - checkout
      - run: wget https://storage.googleapis.com/flutter_infra/releases/beta/macos/flutter_macos_v0.5.1-beta.zip
      - run: unzip flutter_macos_v0.5.1-beta.zip
      - run: export PATH=`pwd`/flutter/bin:$PATH
      - run: cd ios && pod install
      - run: cd .. && flutter doctor
      - run: flutter build ios --release
      - run: cd ios && fastlane deploy_beta

  build-android-beta:
    docker:
      - image: cirrusci/flutter
    steps:
      - checkout
      - run: flutter doctor
      - run: flutter build apk --release
      - run: cd android && fastlane add_plugin appcenter
      - run: fastlane deploy_beta

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build-android-beta:
          filters:
            branches:
              only: beta
      - build-ios-beta:
            filters:
              branches:
                only: beta
