version: 2

jobs:


  build-ios-android:
      macos:
        xcode: "9.4.1"
      steps:
        - checkout
        - run: bash ./scripts/build.sh


workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build-ios-android:
          filters:
            branches:
              only:
              - beta
              - develop
              - master
