# iOS CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/ios-migrating-from-1-2/ for more details
#
version: 2
jobs:
  build-ios-beta:

    # Specify the Xcode version to use
    macos:
      xcode: "9.2"

    steps:
      - checkout

      # Install CocoaPods
      - run:
          name: Install CocoaPods
          command: cd ios && pod install
      - run:
          name: Fastlane iOS
          command: cd ios && fastlane beta

  build-android-beta:

    # Specify the Xcode version to use
    macos:
      xcode: "9.2"

    steps:
      - checkout

      # Install CocoaPods
      - run:
          name: Build flutter
          command: flutter build apk --release
      - run:
          name: Fastlane Android
          command: cd ios && fastlane beta

workflows:
  version: 2
  beta:
    jobs:
      - build-ios-beta
          filters:
              branches:
                only: master
      - build-android-beta
          filters:
              branches:
                only: master